mysite/app_news/urls.py
from django.urls import path
from app_news.views import NewsListView, NewsCreateView, DetailNews, UpdateNews, DeleteNews, NewsByCategoryView
from django.views.defaults import server_error, page_not_found, permission_denied


urlpatterns = [
    path('all_news/', NewsListView.as_view(), name='all_news'),
    path('create_news/', NewsCreateView.as_view(), name='create_news'),
    path('all_news/<int:pk>/', DetailNews.as_view(), name='news_detail'),
    path('all_news/<int:pk>/update/', UpdateNews.as_view(), name='update_new'),
    path('all_news/<int:pk>/delete/', DeleteNews.as_view(), name='delete_new'),
    path('all_cats/<int:pk>/', NewsByCategoryView.as_view(), name='all_cats'),
]

mysite/index/urls.py
from django.urls import path
from index.views import Index

urlpatterns = [
    path('', Index.as_view(), name='index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import handler404, handler403, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('profile/', include('users.urls')),
    path('news/', include('app_news.urls')),
    path('board/', include('app_board.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


hendler404 = 'index.views.page_404'

mysite/app_news/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timezone, datetime, date
from django.urls import reverse



class News(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', null=True)
    title = models.CharField(max_length=300, verbose_name='Название')
    descr = models.TextField(verbose_name='Новость')
    link_new = models.CharField(verbose_name='Ссылка на источник', max_length=500)
    sourse_new = models.CharField(max_length=300, verbose_name='Источник новости')
    created = models.DateTimeField(default=datetime.now(), verbose_name='Дата создания')
    updated = models.DateTimeField(default=datetime.now(), verbose_name='Дата обновления')
    category_new = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Категория', related_name='cats')
    image = models.ImageField(upload_to='img_news/%Y/%m/%d/', verbose_name='Фото новостей', null=True, blank=True)

    def __str__(self):
        return self.author.username

    
    def get_absolute_url(self):
        return reverse('news_detail', kwargs={'pk': self.pk})
    
    def get_upload_url(self):
        return self.image.url
    
    class Meta:
        ordering = ['-created']
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name='Категории', null=True, blank=True)


    def __str__(self):
        return self.title  
    
    def get_absolute_url(self):
        return reverse('category', kwargs={'pk': self.pk})
     
    
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Comment(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, related_name='usercomemnt',
                             null=True, blank=True)
    text = models.TextField(blank=True, null=True, verbose_name='Комментарий')
    news = models.ForeignKey(News, on_delete=models.CASCADE, verbose_name='Пост комментария', related_name='news')
    created = models.DateField(auto_now_add=True, verbose_name='создан')
    updated = models.DateField(auto_now=True, verbose_name='обновлен')
    count_comments = models.IntegerField(verbose_name='Счетчик комментариев', default=0)

    def __str__(self):
        return self.news.title

    def comments_count(self):
        return self.count_comments

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

mysite/app_news/forms.py
from django import forms
from app_news.models import News, Category, Comment


class NewsForm(forms.ModelForm):
    title = forms.CharField(max_length=300, label='Заголовок', widget=forms.TextInput(attrs={'class': 'create__form-input', 'placeholder': 'Введите название *'}))
    descr = forms.CharField(label='Новость', widget=forms.Textarea(attrs={'class': 'create__form-textarea', 'placeholder': 'Введите текст *'}))
    link_new = forms.CharField(label='Ссылка на новость', widget=forms.TextInput(attrs={'class': 'create__form-input', 'placeholder': 'Ссылка *'}), max_length=500)
    sourse_new = forms.CharField(label='Источник новости', widget=forms.TextInput(attrs={'class': 'create__form-input', 'placeholder': 'Источник *'}), max_length=500)
    category_new = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label='Выберете категорию', label='Категория')
    image = forms.ImageField(widget=forms.FileInput(attrs={'placeholder': 'фото поста'}),required=False)
    class Meta:
        model = News
        fields = ('title', 'descr', 'link_new', 'sourse_new', 'category_new', 'image')


class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'comment-text'}))

    class Meta:
        model = Comment
        fields = ('text',)

mysite/app_news/views.py
from typing import Any, Dict
from django.forms.models import BaseModelForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from app_news.models import News, Category, Comment
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from app_news.forms import NewsForm, CommentForm
from django.shortcuts import redirect


class NewsListView(ListView):
    model = News
    template_name = 'app_news/news_list.html'
    context_object_name = 'news'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context
    


class NewsCreateView(LoginRequiredMixin, CreateView):
    model = News
    form_class = NewsForm
    success_url = reverse_lazy('all_news')
    template_name = 'app_news/create_news.html'


    def form_valid(self, form):
        response =  super().form_valid(form)
        self.object.author = self.request.user
        self.object.save()
        return response
    

class DetailNews(DetailView):
    model = News
    template_name = 'app_news/detail_news.html'
    context_object_name = 'info_news'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment'] = Comment.objects.prefetch_related('user').filter(
            news=self.get_object()).order_by('-created')
        context['form'] = CommentForm()
        return context

    def post(self, request, **kwargs):
        news_detail = self.get_object()
        comments_form = CommentForm(request.POST)
        if comments_form.is_valid():
            Comment.objects.create(news=news_detail, user=self.request.user, **comments_form.cleaned_data)
            return redirect('news_detail', pk=news_detail.pk)


class UpdateNews(UpdateView):
    model = News
    template_name = 'app_news/update_news.html'
    form_class = NewsForm
    
    def get_success_url(self):
        return reverse_lazy('news_detail',  kwargs={'pk': self.object.pk})
    

class DeleteNews(DeleteView):
    model = News
    template_name = 'app_news/delete.html'
    success_url = reverse_lazy('all_news')



class NewsByCategoryView(ListView):
    """Представление для отображения новостей по категориям"""
    template_name = 'app_news/category.html'
    model = News
    context_object_name = 'cats'

    def get_queryset(self):
        return News.objects.filter(category_new_id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context

mysite/app_news/templates/app_news/category.html
{% extends 'index/base.html' %}
{% load static %}

{% block title %}
Новости по категории {{ cats.category_new.title}}
{% endblock title %}

{% block content %}
<section class="category">
    <div class="container">
        {% if cats %}    
        {% for cat in cats  %}  
            <div class="category__new">
                {% if cat.image %}
                <div class="category__pic">
                    <a href="{% url 'news_detail' pk=cat.pk %}" class="category__img-link link">
                        <img src="{{cat.image.url}}" alt="" class="category__img">
                    </a>
                </div>
                {% endif %}
                <div class="category__heading-link">
                    <a href="{% url 'news_detail' pk=cat.pk %}" class="category__link link">{{cat.title|truncatechars:"40"}}</a>
                </div>
                <div class="category__date-span">
                    <span class="category_date">{{cat.created|date:"d E Y H:i"}}</span>
                </div>
            </div>
            {% endfor %}
        </div>   
        {% else %}
        <p class="category__not-news">
            В данной категории пока новостей нет
        </p>
        {% endif %}
    </div>
</section>
{% endblock content %}

mysite/app_news/templates/app_news/create_news.html
{% extends 'index/base.html' %}
{% load static %}


{% block title %}
    Создать новость
{% endblock title %}


{% block content %}
<section class="create_new">
    <div class="container">
        <form action="{% url 'create_news' %}" method="post" class="create__new-form" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_title" class="create_new__label">Заголовок:</label>
            {{form.title}}
            <label for="id_descr" class="create_new__label">Новость:</label>
            {{form.descr}}
            <label for="id_link_new" class="create_new__label">Ссылка на источник:</label>
            {{form.link_new}}
            <label for="id_sourse_new" class="create_new__label">Источник:</label>
            {{form.sourse_new}}
            <label for="id_category_new" class="create_new__label">Категории:</label>
            {{form.category_new}}
            <div class="create_new_img-block">
                <label for="id_image" class="create__new__label">Добавить фото:</label>
                <svg class="create_new__svg" xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 96 960 960" width="48"><path d="M453 776h60V610h167v-60H513V376h-60v174H280v60h173v166Zm27.266 200q-82.734 0-155.5-31.5t-127.266-86q-54.5-54.5-86-127.341Q80 658.319 80 575.5q0-82.819 31.5-155.659Q143 347 197.5 293t127.341-85.5Q397.681 176 480.5 176q82.819 0 155.659 31.5Q709 239 763 293t85.5 127Q880 493 880 575.734q0 82.734-31.5 155.5T763 858.316q-54 54.316-127 86Q563 976 480.266 976Zm.234-60Q622 916 721 816.5t99-241Q820 434 721.188 335 622.375 236 480 236q-141 0-240.5 98.812Q140 433.625 140 576q0 141 99.5 240.5t241 99.5Zm-.5-340Z"/></svg>
                <input type="file" name="image" placeholder="фото поста" accept="image/*" id="id_image" class="create__new-img">

            </div>
            <button class="create_new__btn" type="submit">Создать</button>
        </form>
    </div>
</section>
{% endblock content %}
    
    

mysite/app_news/templates/app_news/delete.html
{% extends 'index/base.html' %}
{% load static %}

{% block title %}
     Удаление {{object.title}}
{% endblock %}


{% block content %}

<section class="delete">
    <div class="container">
        <h2 class="delete__quest">Вы точно хотите удалить новость 
            <a href="{% url 'news_detail' pk=object.pk %}" class="delete__link link">
                <span class="delete__span">{{object.title}}</span>
            </a> ?
        </h2>
        <div class="delete__btn-block">
            <div class="delete__no-block"><a href="{% url 'news_detail' pk=object.pk %}" class="delete__no link">Нет</a></div>
            <div class="delete__yes-block">
                <form class="delete__form" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="delete__btn" type="submit">Да</button>
                </form>
            </div>
        </div>
    </div>
</section>
    
{% endblock content %}
    

mysite/app_news/templates/app_news/detail_news.html
{% extends 'index/base.html' %}
{% load static %}

{% block title %}
    {{info_news.title}}
{% endblock %}


{% block content %}
<section class="detail">
    <div class="container"> 
        <div class="detail__back">
            <a href="{% url 'all_news' %}" class="back link">Назад</a> 
        </div>  
        <div class="detail__all">
            {% if info_news.image %}
            <div class="detail__img-block">
                <a href="{{info_news.image.url}}" class="detail__link" target="_blank">
                    <img src="{{info_news.image.url}}" alt="{{info_news.title}}" class="detail__image">
                </a>
            </div>
            {% endif %}
            <h2 class="detail__head">{{info_news.title}}</h2>
            <p class="detail__text">{{info_news.descr}}</p>
            <div class="detail__info-block">
                <span class="detail__sourse">Источник: 
                    <a href="{{info_news.link_new}}" class="detail__link link" target="_blank">{{info_news.sourse_new}}</a>
                </span>
                <span class="detail__created">{{info_news.created|date:"d E Y"}}</span>
            </div>
        </div>
        
        {% if info_news.author == request.user %}
        <a href="{% url 'update_new' pk=info_news.pk %}" class="detail__news-link link">
            <svg class="detail__svg" xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 96 960 960" width="48"><path d="M480 896q-133 0-226.5-93.5T160 576q0-133 93.5-226.5T480 256q85 0 149 34.5T740 385V256h60v254H546v-60h168q-38-60-97-97t-137-37q-109 0-184.5 75.5T220 576q0 109 75.5 184.5T480 836q83 0 152-47.5T728 663h62q-29 105-115 169t-195 64Z"/></svg>
        </a>
        <a href="{% url 'delete_new' pk=info_news.pk %}" class="detail__news-link link">
            <svg class="detail__svg" xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 96 960 960" width="48"><path d="M261 936q-24.75 0-42.375-17.625T201 876V306h-41v-60h188v-30h264v30h188v60h-41v570q0 24-18 42t-42 18H261Zm438-630H261v570h438V306ZM367 790h60V391h-60v399Zm166 0h60V391h-60v399ZM261 306v570-570Z"/></svg>
        </a>
        {% endif %}

        <div class="detail__comment-block">
            {% with comment.count as total_comments %}
                <h2 class="detail__comment-count">Комментарии: ({{ total_comments }})</h2>
            {% endwith %}
                {% if comment %}
                    <ul class="comment_list list">
                    {% for c in comment %}
                        <li class="comment_list-item">
                            <div class="detail__comment-user">
                                <div class="comment_avatar-block">
                                    {% if c.user.profile.avatar %}
                                    <img src="{{c.user.profile.avatar.url }}" alt="{{ c.user.username }}" class="comment_avatar">
                                    {% else %}  
                                    <img src="{% static 'index/img/icon-user.png' %}" alt="{{ c.user.username }}" class="comment_avatar">
                                    {% endif %} 
                                </div>
                                <div class="comment_user">
                                    <span class="comment_username">{{ c.user.username }}</span>
                                </div>
                            </div>
                            <div class="comment_data">
                                <p class="comment_text">{{ c.text }}</p>
                                <span class="comment_date">{{ c.created }}</span>
                            </div>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <p class="comment_no-comments">Пока нет комментариев</p>
                {% endif %}
            </div>

        {% if request.user.is_authenticated %}
        <div class="detail__form-block">
            <form action="{% url 'news_detail' pk=object.pk %}" class="detail__form" method="post">
                {% csrf_token %}
                {{ form.text }}
                <button class="comment__form-btn" type="submit">Отправить</button>
            </form>
         </div>
        {% else %}
        <p class="detail__comment-info">Комментарии могут оставлять только зарегистрированные пользователи</p>
        <a href="{% url 'login' %}">Войти</a> |
        <a href="{% url 'register' %}">Зарегистрироваться</a>
        {% endif %}
    </div>
</section>
{% endblock content %}
    

mysite/app_news/templates/app_news/news_list.html
{% extends 'index/base.html' %}
{% load static %}

{% block title %}
Блок новостей и постов
{% endblock title %}


{% block content %}
<section class="news">
    <div class="container">
        {% if news %}
        <div class="news__cats">
            <h3 class="news__cats-title">Категории:</h3>
            {% for c in category  %}
                <a href="{% url 'all_cats' pk=c.pk %}" class="news__cats-link link">{{c.title}}</a>
            {% endfor %} 
        </div>
        <ul class="news__list list">
            {% for n in news  %}
                <li class="news__list-item">
                    <div class="news__user">
                        <div class="news__pic-block">
                        {% if n.author.profile.avatar %}
                            <img src="{{n.author.profile.avatar.url}}" width="200" height="200" alt="" class="news__ava">
                        {% else %}
                            <img src="{% static 'index/img/icon-user.png' %}" width="200" height="200" alt="" class="news__ava">
                        {% endif %}
                        </div>
                        <div class="news__username">
                            <span class="news__username">{{n.author.username}}</span>
                        </div>
                    </div>
                    <a href="{% url 'news_detail' pk=n.pk %}" class="news__detail-link link"><h3 class="news__head">{{n.title}}</h3></a>
                    <div class="news__info">
                        <span class="news__span">{{n.category_new}}</span>
                        <span class="news__span">{{n.created|date:"d E Y" }}</span>
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% else %}
        <p class="news__not">
            Нет новостей
        </p>
        {% endif %}
        {% if request.user.is_authenticated %}
        <a href="{% url 'create_news' %}" class="news__create link">Создать новость</a>
        {% endif %}
    </div>
</section>
    
{% endblock content %}
    
    

mysite/app_news/templates/app_news/update_news.html
{% extends 'index/base.html' %}
{% load static %}

{% block title %}
Обновить {{object.title}}
{% endblock title %}

{% block content %}
<section class="create_new">
    <div class="container">
        <form method="post" class="create__new-form" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_title" class="create_new__label">Заголовок:</label>
            {{form.title}}
            <label for="id_descr" class="create_new__label">Новость:</label>
            {{form.descr}}
            <label for="id_link_new" class="create_new__label">Ссылка на источник:</label>
            {{form.link_new}}
            <label for="id_sourse_new" class="create_new__label">Источник:</label>
            {{form.sourse_new}}
            <label for="id_category_new" class="create_new__label">Категории:</label>
            {{form.category_new}}
            <div class="create_new_img-block">
                <label for="id_image" class="create_new__label new_l">Добавить фото:</label>
                <svg class="create_new__svg" xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 96 960 960" width="48"><path d="M453 776h60V610h167v-60H513V376h-60v174H280v60h173v166Zm27.266 200q-82.734 0-155.5-31.5t-127.266-86q-54.5-54.5-86-127.341Q80 658.319 80 575.5q0-82.819 31.5-155.659Q143 347 197.5 293t127.341-85.5Q397.681 176 480.5 176q82.819 0 155.659 31.5Q709 239 763 293t85.5 127Q880 493 880 575.734q0 82.734-31.5 155.5T763 858.316q-54 54.316-127 86Q563 976 480.266 976Zm.234-60Q622 916 721 816.5t99-241Q820 434 721.188 335 622.375 236 480 236q-141 0-240.5 98.812Q140 433.625 140 576q0 141 99.5 240.5t241 99.5Zm-.5-340Z"/></svg>
                <input type="file" name="image" placeholder="фото поста" accept="image/*" id="id_image" class="create__new-img">
            </div>
            <button class="create_new__btn" type="submit">Обновить</button>
        </form>
    </div>
</section>
{% endblock content %}