mysite/index/urls.py
from django.urls import path
from index.views import Index

urlpatterns = [
    path('', Index.as_view(), name='index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import handler404, handler403, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('profile/', include('users.urls')),
    path('news/', include('app_news.urls')),
    path('board/', include('app_board.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


hendler404 = 'index.views.page_404'

mysite/users/urls.py
from django.urls import path
from django.urls import path, reverse_lazy
from users.views import ProfileCreate, ProfileDetail, profile_update
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)

urlpatterns = [
    path('register/', ProfileCreate.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('account/<int:pk>/', ProfileDetail.as_view(), name='account'),
    path('account/update/', profile_update, name='update'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html'),name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    
]

mysite/users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', null=True, blank=True,
                             verbose_name='Пользователь')
    full_name = models.CharField(max_length=200, verbose_name='ФИО')
    avatar = models.ImageField(upload_to='avatar/%Y/%m/%d', verbose_name='Аватар', null=True, blank=True)
    city = models.CharField(max_length=200, verbose_name='Город', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')
    updated = models.DateTimeField(auto_now=True, verbose_name='Жата обновления')

    def __str__(self):
        return self.user.username

    def get_upload_url(self):
        return self.avatar.url

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from users.models import Profile


class ProfileForm(UserCreationForm):
    full_name = forms.CharField(required=True, label='', max_length=300, widget=forms.TextInput(attrs={'placeholder': 'Введите ФИО *',
                                                                                        'class': 'register-input'}))
    avatar = forms.ImageField(label='', required=False)
    city = forms.CharField(required=True, label='', max_length=200, widget=forms.TextInput(attrs={
        'placeholder': 'Введите город *', 'class': 'register-input'}))
    username = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя *',
                                                                       'class': 'register-input'}))
    email = forms.CharField(required=True, label='', widget=forms.EmailInput(attrs={'placeholder': 'Введите Email *',
                                                                     'class': 'register-input'}))
    password1 = forms.CharField(required=True, label='', widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль *',
                                                                            'class': 'register-input'}))
    password2 = forms.CharField(required=True, label='', widget=forms.PasswordInput(attrs={'placeholder': 'Повторите пароль *',
                                                                            'class': 'register-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'E-mail'}))

    class Meta:
        model = User
        fields = ['email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city', 'avatar', 'full_name']

mysite/users/views.py
from typing import Any, Dict
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, TemplateView, ListView
from users.forms import ProfileForm, UserUpdateForm, ProfileUpdateForm
from users.models import Profile
from app_news.models import News


class ProfileCreate(CreateView):
    model = User
    form_class = ProfileForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        response = super().form_valid(form)
        full_name = form.cleaned_data['full_name']
        city = form.cleaned_data['city']
        avatar = form.cleaned_data['avatar']
        Profile.objects.create(user=self.object,
                               full_name=full_name,
                               city=city,
                               avatar=avatar)
        
        return response


class ProfileDetail(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'users/account.html'
    context_object_name = 'account'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        user_posts = News.objects.filter(author=self.request.user)
        context =  super().get_context_data(**kwargs)
        context['user_posts'] = user_posts
        return context


@login_required
def profile_update(request):
    """Представление смены информации о пользователе"""
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('account')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/update_profile.html', context)

mysite/users/templates/users/account.html
{% extends 'index/base.html' %}
{% load static %}
{%block title%}{{request.user.username}}{%endblock%}
{% block content %}
    <section class="account">
        <div class="container">
           <div class="account__user-block">
               <div class="account__img-block">
                   {% if account.avatar %}
                   <a href="{{account.avatar.url}}">
                       <img src="{{account.avatar.url}}" alt="{{account.user.username}}" class="account__photo">
                   </a>
                   {% else %}
                   <img src="{% static 'index/img/icon-user.png' %}" alt="{{account.user.username}}" class="account__photo">
                   {% endif %}
               </div>
               <div class="account__user-info">
                   <ul class="account__list list">
                       <li class="account__list-item">
                           <span class="account__title">Имя пользователя: </span>
                           {{ account.user.username }}
                       </li>
                       <li class="account__list-item">
                           <span class="account__title">ФИО: </span>
                           {{ account.full_name }}
                       </li>
                       <li class="account__list-item">
                           <span class="account__title">E-mail: </span>
                           {{ account.user.email }}
                       </li>
                       <li class="account__list-item">
                           <span class="account__title">Город: </span>
                           {{ account.city }}
                       </li>
                   </ul>
                   <a class="account__update-link link" href="{% url 'update' %}">Обновить</a>
               </div>
           </div>
           <div class="account__myposts">
            <h2 class="posts__heading">Мои публикации</h2>
            {% if user_posts %}
            {% for my_post in user_posts  %}
            <h3 class="posts__head"><a href="{% url 'news_detail' pk=my_post.pk %}" class="posts__link link">{{my_post.title}}</a></h3>
            {% endfor %}
            {% else %}
                <p class="posts__not">У вас пока нет публикаций</p>
            {% endif %}
           </div>
        </div>
    </section>
{% endblock %}

mysite/users/templates/users/login.html
{% extends 'index/base.html' %}
{% block title %}Вход{% endblock %}

{% block content %}
<section class="login">
    <div class="container">
        <form method="post" class="login__form" action="{% url 'login' %}">
            {% csrf_token %}
            {% if form.non_field_errors %}
             {% for error in form.non_field_errors %}
                <div class="form-error">{{ error }}</div>
            {% endfor %}
            {% endif %}
            <input type="text" name="username" value="admin" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username" class="login-input" placeholder="Введите имя пользователя">
            <input type="password" name="password" autocomplete="current-password" required="" id="id_password" class="login-input" placeholder="Введите пароль">
            <button type="submit" class="register__btn loginng">Войти</button>
            <a href="{% url 'password_reset' %}" class="login__change-password link">Забыли пароль?</a>
        </form>
        
    </div>
</section>
{% endblock %}

mysite/users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

mysite/users/templates/users/password_reset_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'index/img/django.ico' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="{% static 'index/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/media.css' %}">
    <title>Сброс пароля</title>
</head>
<body>
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="header__top-info">
                    <div class="header__date-block">
                        <span class="header__date">{% now 'j E Y' %}</span>
                    </div>
                    <div class="header__top-logo">
                        <a href="/" class="header__bottom-logo link">MySite</a>
                    </div>
                </div>
            </div>
        </div>        
    </header>
    <section class="complete">
        <div class="container">
            <h2 class="complete__heading">Все получилось !!!</h2>
            <p class="complete__descr">Ваш пароль был изменен. Вы можете 
                <a href="{% url 'login' %}" class="complete__link link">
                    войти на сайт
                </a>
            </p>
        </div>
    </section>
</body>
</html>

mysite/users/templates/users/password_reset_confirm.html
{% extends 'index/base.html' %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<h2>Сброс Вашего пароля</h2>
{% if validlink %}
<p>Пожалуйста, введите свой новый пароль дважды:</p>
<form action="." method="post">
 {{ form.as_p }}
 {% csrf_token %}
 <p><input type="submit" value="Сменить пароль"/></p>
</form>
{% else %}
<p>Ссылка для сброса пароля была недействительной, возможно, потому, 
    что она уже использовалась. Пожалуйста, запросите сброс нового пароля.</p>
{% endif %}
{% endblock %}

mysite/users/templates/users/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'index/img/django.ico' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="{% static 'index/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/media.css' %}">
    <title>Сброс пароля</title>
</head>
<body>
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="header__top-info">
                    <div class="header__date-block">
                        <span class="header__date">{% now 'j E Y' %}</span>
                    </div>
                    <div class="header__top-logo">
                        <a href="/" class="header__bottom-logo link">MySite</a>
                    </div>
                </div>
            </div>
        </div>        
    </header>
    <section class="done">
        <div class="container">
            <h2 class="done__heading">Сброс Вашего пароля</h2>
            <p class="done__descr">Мы отправили вам по электронной почте инструкции по установке вашего пароля.</p>
            <p class="done__descr">Если вы не получили электронное письмо, пожалуйста, убедитесь, что вы ввелиадрес, по которому регистрировались.</p>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'index/js/index.js' %}"></script>  
    </body>
    </html>

mysite/users/templates/users/password_reset_email.html
Вы запросили сброс пароля для электронной почты {{ email }}. Перейди по ссылке
ниже:
{{ protocol }}://{{ domain  }}{% url "password_reset_confirm" uidb64=uid token=token %}
Ваше имя пользователя, если вы забыли: {{ user.get_username }}

mysite/users/templates/users/password_reset_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'index/img/django.ico' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="{% static 'index/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/media.css' %}">
    <title>Сброс пароля</title>
</head>
<body>
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="header__top-info">
                    <div class="header__date-block">
                        <span class="header__date">{% now 'j E Y' %}</span>
                    </div>
                    <div class="header__top-logo">
                        <a href="/" class="header__bottom-logo link">MySite</a>
                    </div>
                </div>
            </div>
        </div>        
    </header>
    <section class="reset">
        <div class="container">
            <h2 class="reset__heading">Забыли пароль ?</h2>
            <p class="reset__descr">Введите свой адрес электронной почты, чтобы получить новый пароль.</p>
            <form method="post" class="reset__form">
                {% csrf_token %}
                {% if form.email.errors %} {{ form.email.errors }} {% endif %}
                <input type="email" name="email" autocomplete="email" maxlength="254" required="" id="id_email" class="reset__email" placeholder="Введите Email">
                <button class="reset_btn" type="submit">Отправить</button>
            </form>
        </div>
    </section>
<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'index/js/index.js' %}"></script>  
</body>
</html>

mysite/users/templates/users/register.html
{% extends 'index/base.html' %}
{% block title %}Регистрация{% endblock %}

{% block content %}
<section class="register">
    <div class="container">
        <div class="register__block">
            <div class="register__descr">
                <h2 class="register__descr-heading">Регистрация</h2>
                <p class="register__text">
                    Здесь, Вы можете пройти лёгкую регистрацию!
                    Все пароли зашифрованы и даже человек, который написал приложение на Django не будет знать его.
                    Об этом позаботились создатели фреймворка Django.
                </p>
            </div>
            <div class="register__form">
                <form class="form" enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    {% for error in form.username.errors %}
                    <div class="form-error">{{ error|escape }}</div>
                    {% endfor %}
                    {{ form.username }}
                    {% for error in form.full_name.errors %}
                    <div class="form-error">{{ error|escape }}</div>
                    {% endfor %}
                    {{ form.full_name }}
                    {% for error in form.email.errors %}
                    <div class="form-error">{{ error|escape }}</div>
                    {% endfor %}
                    {{ form.email }}
                    {% for error in form.city.errors %}
                    <div class="form-error">{{ error|escape }}</div>
                    {% endfor %}
                    {{ form.city }}
                    {% for error in form.password1.errors %}
                    <div class="form-error">{{ error|escape }}</div>
                    {% endfor %}
                    {{ form.password1 }}
                    {% for error in form.password2.errors %}
                    <div class="form-error">{{ error|escape }}</div>
                    {% endfor %}
                    {{ form.password2 }}
                    <div class="register__avatar-block">
                        <svg class="register__svg" xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 96 960 960" width="48"><path d="M453 776h60V610h167v-60H513V376h-60v174H280v60h173v166Zm27.266 200q-82.734 0-155.5-31.5t-127.266-86q-54.5-54.5-86-127.341Q80 658.319 80 575.5q0-82.819 31.5-155.659Q143 347 197.5 293t127.341-85.5Q397.681 176 480.5 176q82.819 0 155.659 31.5Q709 239 763 293t85.5 127Q880 493 880 575.734q0 82.734-31.5 155.5T763 858.316q-54 54.316-127 86Q563 976 480.266 976Zm.234-60Q622 916 721 816.5t99-241Q820 434 721.188 335 622.375 236 480 236q-141 0-240.5 98.812Q140 433.625 140 576q0 141 99.5 240.5t241 99.5Zm-.5-340Z"/></svg>
                        <input type="file" name="avatar" accept="image/*" id="id_avatar" class="avatar-input">
                    </div>
                    <button class="register__btn" type="submit">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mysite/users/templates/users/update_profile.html
{% extends 'index/base.html' %}
{% load static %}
{% block content %}
<section class="update">
    <div class="container">
        <form class="update__form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="update__avatar-block">
                {% if request.user.profile.avatar %}
                <a href="{{request.user.profile.avatar.url}}" class="update__link link">
                    <img src="{{request.user.profile.avatar.url}}" alt="" class="update__img">
                </a>
                <div class="update__avtar-input">
                    <svg class="update__svg" xmlns="http://www.w3.org/2000/svg" height="80" viewBox="0 96 960 960" width="80"><path d="M453 776h60V610h167v-60H513V376h-60v174H280v60h173v166Zm27.266 200q-82.734 0-155.5-31.5t-127.266-86q-54.5-54.5-86-127.341Q80 658.319 80 575.5q0-82.819 31.5-155.659Q143 347 197.5 293t127.341-85.5Q397.681 176 480.5 176q82.819 0 155.659 31.5Q709 239 763 293t85.5 127Q880 493 880 575.734q0 82.734-31.5 155.5T763 858.316q-54 54.316-127 86Q563 976 480.266 976Zm.234-60Q622 916 721 816.5t99-241Q820 434 721.188 335 622.375 236 480 236q-141 0-240.5 98.812Q140 433.625 140 576q0 141 99.5 240.5t241 99.5Zm-.5-340Z"/></svg>
                    <input type="file" name="avatar" accept="image/*" id="id_avatar" class="update__avatar-file">
                </div>
            {% else %}
                     <a href="#" class="update__link link">
                        <img src="{% static 'index/img/icon-user.png' %}" alt="" class="update__img">
                    </a>
                    <div class="update__avtar-input">
                        <svg class="update__svg" xmlns="http://www.w3.org/2000/svg" height="80" viewBox="0 96 960 960" width="80"><path d="M453 776h60V610h167v-60H513V376h-60v174H280v60h173v166Zm27.266 200q-82.734 0-155.5-31.5t-127.266-86q-54.5-54.5-86-127.341Q80 658.319 80 575.5q0-82.819 31.5-155.659Q143 347 197.5 293t127.341-85.5Q397.681 176 480.5 176q82.819 0 155.659 31.5Q709 239 763 293t85.5 127Q880 493 880 575.734q0 82.734-31.5 155.5T763 858.316q-54 54.316-127 86Q563 976 480.266 976Zm.234-60Q622 916 721 816.5t99-241Q820 434 721.188 335 622.375 236 480 236q-141 0-240.5 98.812Q140 433.625 140 576q0 141 99.5 240.5t241 99.5Zm-.5-340Z"/></svg>
                        <input type="file" name="avatar" accept="image/*" class="update__avatar-file">
                    </div>
            {% endif %}
            </div>
            <label for="id_email" class="update__label">Email:</label>
            <input class="update__user-input" type="email" name="email" value="{{request.user.email}}" placeholder="E-mail" required="" id="id_email">
            <label for="id_city" class="update__label">Город:</label>
            <input class="update__user-input" type="text" name="city" value="{{request.user.profile.city}}" maxlength="200" id="id_city">
            <label for="id_full_name" class="update__label">ФИО:</label>
            <input class="update__user-input" type="text" name="full_name" value="{{request.user.profile.full_name}}" maxlength="200" required="" id="id_full_name">
            <button type="submit" class="register__btn">Обновить</button>
        </form>
    </div>
</section>
{% endblock %}